# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = '2'

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = 'ubuntu/trusty64'

  config.vm.network 'forwarded_port', guest: 8888, host: 8888
  config.vm.network 'forwarded_port', guest: 8443, host: 8443

  config.vm.provision 'file', source: '~/.gitconfig', destination: '.gitconfig'
  config.vm.provision 'file', source: 'files/config.json', destination: 'config.json'
  config.vm.provision 'shell', path: 'provision.sh'

  config.vm.synced_folder '../', '/home/vagrant/workspace'

  config.ssh.forward_agent = true

  if Vagrant.has_plugin?('vagrant-proxyconf') && ENV.has_key?('http_proxy')
    config.proxy.http = ENV['http_proxy']
    config.proxy.no_proxy = 'localhost,127.0.0.1'
  end
end
