# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = '2'

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = 'ubuntu/xenial64'

  config.vm.network 'forwarded_port', guest: 8888, host: 8888
  config.vm.network 'forwarded_port', guest: 8443, host: 8443

  config.vm.provision 'file', source: '~/.gitconfig', destination: '.gitconfig'
  config.vm.provision 'shell', path: 'provision.sh'

  config.vm.synced_folder '../', '/home/ubuntu/workspace'

  config.ssh.forward_agent = true
end
