#!/bin/bash

# Stop the appserver:
stop piksha

#Remove the user
userdel piksha

# Remove installed app dependencies
rm -rf /var/log/piksha
rm -rf /opt/piksha/node_modules
rm -rf /opt/piksha/tmp
rm -rf /opt/piksha/.forever
rm -rf /opt/piksha/.node-gyp
rm -rf /opt/piksha/.npm
